import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "./Navbar";
import Footer from "./Footer";
import TeachersList from "./TeachersList";
import CategoryList from "./CategoryList";
import ScheduleList from "./ScheduleList";
import Navbarr from "./Navbarr";
import PageWrapper from "./page-warapper";
export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Teacher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbarr />
      <PageWrapper>
        <div className="container mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-5 gap-0">
            <div className="col-span-3">
              <ScheduleList />
            </div>
            <div className="col-span-2">
              <CategoryList />
            </div>
          </div>
        </div>
      </PageWrapper>
      <Footer></Footer>
    </div>
  );
}
